title: Joe Pierce
description: Senior Python Engineer specialising in backend, data and AI systems
url: "https://joe-pierce.github.io"

markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
